// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylulnyvhgdrrwgnmmjyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsdWxueXZoZ2Rycndnbm1tanlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDg1MTgsImV4cCI6MjA2OTcyNDUxOH0.gpn6QaZhym-YUZYUahpbjWUQK19x6wI2ncw8Gon9OvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});